version: 0.6.{build}
image: Visual Studio 2017
configuration: Release

# Build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache'  # NuGet v3

# Enable patching of AssemblyInfo.* files
init:
  - ps: |
      $version = new-object System.Version $env:APPVEYOR_BUILD_VERSION
      $env:PackageVersion = "{0}.{1}.{2}" -f $version.Major, $version.Minor, $version.Build

before_build:
  - nuget restore

assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_file_version: '$(APPVEYOR_BUILD_VERSION)'
  assembly_informational_version: '$(APPVEYOR_BUILD_VERSION)'

build:
  verbosity: minimal

after_build:
  - ps: nuget pack build\nuspecs\UmbMapper.nuspec -version "$env:PackageVersion"
  - ps: nuget pack build\nuspecs\UmbMapper.NuPickers.nuspec -version "$env:PackageVersion"
  - ps: nuget pack build\nuspecs\UmbMapper.Archetype.nuspec -version "$env:PackageVersion"

artifacts:
  - path: 'UmbMapper*.nupkg'