version: 0.5.{build}
image: Visual Studio 2017
configuration: Release

# Build cache to preserve files/folders between builds
cache:
  - packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified
  - '%LocalAppData%\NuGet\Cache'    # NuGet < v3
  - '%LocalAppData%\NuGet\v3-cache'  # NuGet v3

# Enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "0.5.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

build:
  verbosity: minimal